services:
  mongo:
    image: mongo:4.4.3-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo

  mmo-api:
    image: mmo-api:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_CONNECTION_STRING: mongodb://root:password@mongo:27017
    depends_on:
      - mongo
